# Generated by Django 4.1.2 on 2022-10-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('type', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='menuitems')),
            ],
        ),
    ]
